# Generated by Django 3.1.2 on 2020-10-20 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lebensmittel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'lebensmittel',
            },
        ),
        migrations.CreateModel(
            name='Rezepte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('beschreibung', models.TextField()),
            ],
            options={
                'db_table': 'rezepte',
            },
        ),
        migrations.CreateModel(
            name='RezepteLebensmittel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lebensmittelId', models.ForeignKey(db_column='lebensmittel_id', on_delete=django.db.models.deletion.DO_NOTHING, to='receipe.lebensmittel')),
                ('rezepteId', models.ForeignKey(db_column='rezepte_id', on_delete=django.db.models.deletion.DO_NOTHING, to='receipe.rezepte')),
            ],
            options={
                'db_table': 'rezepte_has_lebensmittel',
                'unique_together': {('rezepteId', 'lebensmittelId')},
            },
        ),
    ]
