# Generated by Django 3.1.2 on 2020-10-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezepte',
            old_name='name',
            new_name='namen',
        ),
        migrations.AddField(
            model_name='rezeptelebensmittel',
            name='bild_link',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezeptelebensmittel',
            name='menge',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rezeptelebensmittel',
            name='id',
            field=models.IntegerField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
