# Generated by Django 3.1.2 on 2020-10-24 08:15

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models.fields.bit


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201014_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_coach',
            field=django_mysql.models.fields.bit.Bit1BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_user',
            field=django_mysql.models.fields.bit.Bit1BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='stripe_access_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='stripe_user_id',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='StripePaymentDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_detail', models.TextField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stripe_client', to='user.person')),
                ('coach_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stripe_coach', to='user.person')),
            ],
            options={
                'db_table': 'stripe_payment_det',
            },
        ),
    ]
